from main.api import api


def test_api_json_openapi(admin_client):
    """Test endpoint which provide autogenerated openapi.json"""
    response = admin_client.get(f"{api.root_path}{api.openapi_url[1:]}")
    assert response.status_code == 200
    assert response.json()["info"]["title"] == "NinjaAPI"


def test_api_docs(admin_client):
    """Test the /api/docs endpoint"""
    response = admin_client.get(f"{api.root_path}{api.docs_url[1:]}")
    assert response.status_code == 200


def test_visitor_cannot_access_api(client):
    """Test that visitor cannot access API"""
    response = client.get(f"{api.root_path}{api.docs_url[1:]}")
    assert response.status_code == 302
    assert response.url == f"/admin/login/?next={api.root_path}{api.docs_url[1:]}"
