# Generated by Django 4.2.7 on 2023-11-20 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LmTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the task",
                        max_length=128,
                        verbose_name="Name",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="The gguf model file to use for this task",
                        max_length=255,
                        verbose_name="Model file",
                    ),
                ),
                ("template", models.TextField(verbose_name="Prompt template")),
                (
                    "params",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="llm.inferenceparamspreset",
                    ),
                ),
            ],
        ),
    ]
