# Generated by Django 4.2.7 on 2023-11-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0002_lmtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="lmtask",
            name="description",
            field=models.TextField(default="", verbose_name="Task description"),
            preserve_default=False,
        ),
    ]
